#!/bin/bash
"""
Shutsdown one container then attempts to make all requests 
Use: ./avtest [DOCKER_CONTAINER_ID]
"""
CWD="`pwd`";
docker stop $1
echo one container shutdown
for req in `cat requests`
do
    curl -X PUT $req 
done
