#!/bin/bash
"""
Script to set up Cassandra cluster.
Sample use: ./startCassandraCluster user@192.168.22.130 user@192.168.22.131 ...
Master node will be on the first server provided
"""

USAGE="Usage: $0 USER@IP1 USER@IP2 USER@IP3 ..."

# Set @ as delimiter to split input
IFS='@'


if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

MASTER="$1"
while (( "$#" )); do
	#Read user and IP
	read -a strarr <<< "$1"

	#Grab the IP
	IP=${strarr[1]}

	if [ "$1" = "$MASTER" ]; 
	then
		MASTERIP=$IP
		COMMAND="docker run --name cassandra-node -d -e CASSANDRA_BROADCAST_ADDRESS=$IP -p 7000:7000 -p 9042:9042 cassandra"
	else
		COMMAND="docker run --name cassandra-node -d -e CASSANDRA_BROADCAST_ADDRESS=$IP -p 7000:7000 -p 9042:9042 -e CASSANDRA_SEEDS=$MASTERIP cassandra"
	fi
	ssh "$1" "docker container stop cassandra-node"
	ssh "$1" "docker container rm cassandra-node"
	ssh "$1" "$COMMAND"
	
	while true;
	do
		sleep 5
		STATUS=$(docker exec -it cassandra-node nodetool status | grep -e $IP)
		STATUSUN=$(echo $STATUS | grep -e "UN")
		echo $STATUS
		[[ ! -z "$STATUSUN" ]] && break;
	done;
	shift
done
