#!/bin/bash
USAGE="Usage: $0 USER@IP1 USER@IP2 USER@IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

docker container stop cassandra-node
docker container rm cassandra-node
shift

while (( "$#" )); do
	ssh $1 "docker container stop cassandra-node"
	ssh $1 "docker container rm cassandra-node"
	shift
done
