#!/bin/bash
USAGE="Usage: $0 IP1 IP2 IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

docker stack rm urlShortner

while (( "$#" )); do
	
	ssh student@$1 "docker swarm leave --force"
	shift
done


















