#!/bin/bash
USAGE="Usage: $0 user@IP1 user@IP2 user@IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

docker stack rm urlShortner

while (( "$#" )); do
	ssh $1 "docker swarm leave --force"
	shift
done


















