#!/bin/bash
USAGE="Usage: $0 IP1 IP2 IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

MASTER="$1"
while (( "$#" )); do
	if [ "$1" = "$MASTER" ]; 
	then
		COMMAND="docker swarm init --advertise-addr $1"
	fi
		
	ssh student@$1 "docker swarm leave --force"
	ssh student@$1 "$COMMAND"

	if [ "$1" = "$MASTER" ];
	then
		COMMAND=$(ssh student@$1 "docker swarm join-token worker | grep docker")
	fi
	
	shift
done

docker login
docker build -t obsoleete/a2_new:latest .
docker push obsoleete/a2_new:latest
docker stack deploy -c docker-compose.yml urlShortner
echo "Wait 15 seconds for docker to deploy"

for i in {0..2..1}
do
        sleep 3s
        echo "Waiting to deploy..."
        sleep 2s
done

echo "Deployed."



