#!/bin/bash
# Script to deploy the stack with all the necessary docker services. 
# Sample use: ./startDockerService user@192.168.22.130 user@192.168.22.131 ...
# Manager node will be the first node provided 

USAGE="Usage: $0 USER@IP1 USER@IP2 USER@IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

# Set @ as delimiter to split input
IFS='@'

#Read user and IP
read -a strarr <<< "$1"

#Grab the IP
IP=${strarr[1]}

MASTER="$1"
while (( "$#" )); do

	if [ "$1" = "$MASTER" ]; 
	then
		COMMAND="docker swarm init --advertise-addr $IP"
	fi
		
	ssh "$1" "docker swarm leave --force"
	ssh "$1" "$COMMAND"

	if [ "$1" = "$MASTER" ];
	then
		COMMAND=$(ssh "$1" "docker swarm join-token worker | grep docker")
	fi
	
	shift
done

# Building, pushing image and deploying stack
# docker login
# docker build -t moazmuha/urlshortner:latest .
# docker push moazmuha/urlshortner:latest
docker build -t urlshortner:latest .
docker stack deploy -c docker-compose.yml urlShortner
echo "Wait 15 seconds for docker to deploy"

for i in 0 1 2
do
        sleep 3s
        echo "Waiting to deploy..."
        sleep 2s
done

echo "Deployed."



